### ISSUE TITLE
Mispelled tag

### ISSUE THREAD

**Issue by DiscoverProgramming** [IntegerAlex/ts-strict-setup#11]
# Description
Cool project! Just thought I should mention that you misspelled the TypeScript tag with "tyepscript". Other than that, everything looks good. I wish you the best of luck!

**Comment by IntegerAlex** [comment]
Done, Can you please share the word for this project. 
I will be adding features like  ts+express , react+tsx , es6+

**Comment by IntegerAlex** [comment]
resolved
